### ISSUE TITLE
Override the odata Get method to include a ODataQueryOptions opts parameter and apply custom code

### ISSUE THREAD

**Issue by dialeggio** [aspnetboilerplate/sample-odata#10]
Hi guys, can you provide an example on how to override the Get odata method in a AbpODataEntityController controller to allow a custom functionality to apply to the repository and result set, ie apply additional filter by clauses to the result etc.

Regards
David

**Comment by dialeggio** [comment]
Just to clarify, I want to override the Get method in the AbpODataEntityController to include a ODataQueryOptions parameter so I can access the filter options being passed into the odata get call.

**Comment by ismcagdas** [comment]
@dialeggio do you mean something like this https://github.com/aspnetboilerplate/sample-odata/blob/master/AbpODataDemo-Core/aspnet-core/src/AbpODataDemo.Web.Core/Controllers/PersonsController.cs#L26 ?
