### ISSUE TITLE
Version Conflict on updation of ABP framework to 3.3.0 and Microsoft.AspNet.OData to 6.1.0

### ISSUE THREAD

**Issue by Bijayakumar1990** [aspnetboilerplate/sample-odata#6]
Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Reference the package directly from the project to resolve this issue. 
 kare4u.Web.Host -> kare4u.Web.Core -> kare4u.Application -> kare4u.Core -> Abp.ZeroCore.EntityFrameworkCore 3.3.0 -> Abp.EntityFrameworkCore 3.3.0 -> Microsoft.EntityFrameworkCore 2.0.1 -> Microsoft.Extensions.DependencyInjection 2.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.0.0)

 kare4u.Web.Host -> kare4u.Web.Core -> Microsoft.AspNet.OData 6.1.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0 && < 2.0.0).

**Comment by hikalkan** [comment]
Duplicate: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2670

**Comment by acjh** [comment]
Try downgrading **Abp.Web.Api.OData** to **v2.3.0**.

**Comment by Bijayakumar1990** [comment]
Its not that Abp.Web.Api.OData has the conflict. ABP 3.3.0 has a dependency on Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.0.0). I have to downgrade the abp framework then. And I don't want to downgrade it.

**Comment by Bijayakumar1990** [comment]
Its resolved when I updated the abp framework to version 3.
