### ISSUE TITLE
DB entity is not updated when submitting a OData Patch request with changes

### ISSUE THREAD

**Issue by dialeggio** [aspnetboilerplate/sample-odata#9]
When I submit Patch Request with changes for an entity, the Delta Entity parameter doesn't list the changed fields and hence doesn't update the DB with the changes. 

Assemblies affected:
Abp.AspNetCore.OData v3.6.2
Microsoft.AspNet.WebApi.OData v5.7.0
Microsoft.Data.OData v5.8.3

Reproduce steps

using the aspnet boilerplate odata example that can be found here:
https://github.com/aspnetboilerplate/sample-odata

The attached image shows the patch requests made to update the Persons Entity. 

Basically in the Patch function the Delta parameter does not list any of the changes made in the request. 

Here is the snippet from the controller:

        public override Task<IActionResult> Patch([FromODataUri] int key, Delta<Person> entity)
        {
            return base.Patch(key, entity);
        }

Expected result:

The Delta Entity parameter in the Patch controller method should list the changes submitted in the odata patch request and therefore update the DB with the changes.

Actual result:

The Delta Entity parameter lists no changes to the entity and the DB record is not updated with any changes from the request.

![odatapatchrequest](https://user-images.githubusercontent.com/19598834/40535104-ab5fe550-5ff7-11e8-8e65-c6338dc62c03.jpg)

**Comment by acjh** [comment]
Do `Put` and `Post` work?

**Comment by dialeggio** [comment]
Get works, haven’t tried put or post

**Comment by acjh** [comment]
I reckon those don't work too.
- Issue closed without fix: https://github.com/OData/WebApi/issues/1208#issuecomment-380512814
- PR merged with mention: https://github.com/aspnetboilerplate/aspnetboilerplate/pull/2872

Related issue: https://github.com/OData/WebApi/issues/1446

**Comment by rodrigozoff** [comment]
For me this code worked and resolved my problem:

`      public override async Task<IActionResult> Patch([FromODataUri] int key, [FromBody] Delta<Competencia> entity)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var dbLookup = await Repository.GetAsync(key);
            if (dbLookup == null)
            {
                return NotFound();
            }

            entity.Patch(dbLookup);
            
            return new UpdatedODataResult<Competencia>(this.Repository.Get(key));
        }`
